site_name: Guia de Serviços
pages:
- [index.md, Principal]
- ['estrategia/index.md', 'Estratégia', 'Introdução']
- ['estrategia/personas.md', 'Estratégia', 'Personas']
- ['estrategia/jornadas.md', 'Estratégia', 'Jornadas']
- ['estrategia/principios.md', 'Estratégia', 'Princípios']
- ['estrategia/modelomaturidade.md', 'Estratégia', 'Modelo de Maturidade']
- ['estrategia/kpis.md', 'Estratégia', 'Métricas']
- ['estrategia/escolhaservicos.md', 'Estratégia', 'Critérios para Escolha de Serviços']
- ['estrategia/etapasoferta.md', 'Estratégia', 'Etapas da Oferta de Serviços']
- ['desenvolvimento/introducao.md', 'Desenvolvimento', 'Introdução']
- ['desenvolvimento/ambientes.md', 'Desenvolvimento', 'Ambientes']
- ['desenvolvimento/elasticsearch.md', 'Desenvolvimento', 'Elasticsearch']
- ['desenvolvimento/dados-criptografados.md', 'Desenvolvimento', 'Dados Criptografados']
- ['desenvolvimento/execucao.md', 'Desenvolvimento', 'Execução']
- ['desenvolvimento/testes.md', 'Desenvolvimento', 'Testes']
- ['desenvolvimento/bugs.md', 'Desenvolvimento', 'Bugs']
- ['sobre/links.md', 'Sobre o projeto', 'Referências']
- ['sobre/autores.md', 'Sobre o projeto', 'Autores']
- ['sobre/contato.md', 'Sobre o projeto', 'Contato']
- ['sobre/license.md', 'Sobre o projeto', 'Licença']

theme: readthedocs
repo_url: https://github.com/servicosgovbr/guia-de-servicos
