site_name: Guia de Serviços
pages:
- [index.md, Principal]
- [desenvolvimento.md, Desenvolvimento]
- [contato.md, Contato]
- [links.md, Referências]
- [autores.md, Autores]
- [license.md, Licença]
theme: readthedocs

