site_name: Guia de Serviços
pages:
- [index.md, 'Principal']
- [introducao/index.md, 'Introdução']
- [principios/index.md, 'Princípios']
- [sobre-o-projeto/index.md, 'Sobre o Projeto']
- [servicos/index.md, 'Serviços']
- [metricas/index.md, 'Métricas']
- [metodologia-de-desenvolvimento/index.md, 'Metodologia de Desenvolvimento']
- [desenvolvimento/index.md, 'Desenvolvimento']

theme: readthedocs
repo_url: https://github.com/servicosgovbr/guia-de-servicos
markdown_extensions: [admonition]
