site_name: Guia de Serviços
pages:
- [index.md, Principal]
- ['estrategia/index.md', 'Estratégia', 'Introdução']
- ['estrategia/personas.md', 'Estratégia', 'Personas']
- ['estrategia/jornadas.md', 'Estratégia', 'Jornadas']
- ['desenvolvimento/introducao.md', 'Desenvolvimento', 'Introdução']
- ['desenvolvimento/ambientes.md', 'Desenvolvimento', 'Ambientes']
- ['desenvolvimento/elasticsearch.md', 'Desenvolvimento', 'Elasticsearch']
- ['desenvolvimento/dados-criptografados.md', 'Desenvolvimento', 'Dados Criptografados']
- ['desenvolvimento/execucao.md', 'Desenvolvimento', 'Execução']
- ['desenvolvimento/testes.md', 'Desenvolvimento', 'Testes']
- ['desenvolvimento/bugs.md', 'Desenvolvimento', 'Bugs']
- ['sobre/links.md', 'Sobre o projeto', 'Referências']
- ['sobre/autores.md', 'Sobre o projeto', 'Autores']
- ['sobre/contato.md', 'Sobre o projeto', 'Contato']
- ['sobre/license.md', 'Sobre o projeto', 'Licença']

theme: readthedocs
repo_url: https://github.com/thoughtworks/guia-de-servicos-frontend
