spring:
  main:
    show-banner: false

  thymeleaf:
    cache: false

endpoints:
  health:
    sensitive: false

server:
  port: ${port:8080}

mail:
  protocol: smtp
  host: localhost
  port: 2500
  timeout: 5000
  smtp:
    auth: false
    starttls: false
  from: nao-responda@servicos.gov.br
  to: servicos@planejamento.gov.br
  username:
  password:

gds:
  permitir-robos: false
  importar-automaticamente: false
  piwik:
    enabled: false
    url: "https://estatisticas.presidencia.gov.br/"
    token: ""
    site: 2
  destaques:
    servicos:
      - retificadora-on-line-extrato-da-dirpf
      - aposentadoria-por-invalidez
      - vistas-de-processo
  conteudo:
    linhasDaVida:
      abrir-um-negocio: "Administrar um negócio"
      administrar-um-negocio: "Administrar um negócio"
      adolescentes: "Adolescentes"
      aposentar-se: "Aposentar-se"
      ter-uma-casa: "Ter uma casa"
      ter-uma-familia: "Ter uma família"
      aproveitando-o-tempo-livre: "Aproveitar o tempo livre"
      cuidando-da-saude: "Cuidar da saúde"
      emitindo-meus-documentos: "Emitir seus Documentos"
      estudando: "Estudar"
      garantindo-meus-direitos: "Garantir seus direitos"
      indo-para-outro-pais: "Viajar para o exterior"
      mantendo-um-veiculo: "Manter um veículo"
      meu-negocio: "Administrar um negócio"
      obter-credito-e-apoio-financeiro: "Obter crédito e apoio financeiro"
      pagando-contas-e-impostos: "Pagar contas e impostos"
      prestando-servico-militar: "Prestar serviço militar"
      procurando-emprego: "Procurar emprego"
      trabalhando: "Trabalhar"
      ter-filhos: "Ter uma família"
    orgaos:
      arquivo-nacional: "Arquivo Nacional"
      banco-central-do-brasil: "Banco Central do Brasil (BCB)"
      banco-central-do-brasil-bcb: "Banco Central do Brasil (BCB)"
      comissao-de-anistia: "Comissão de Anistia"
      conselho-administrativo-de-defesa-economica-cade: "Conselho Administrativo de Defesa Econômica (CADE)"
      defensoria-publica-da-uniao-dpu: "Defensoria Pública da União (DPU)"
      departamento-de-policia-federal: "Departamento de Polícia Federal (DPF)"
      departamento-de-policia-rodoviaria-federal: "Departamento de Polícia Rodoviária Federal (DPRF)"
      departamento-de-policia-rodoviaria-federal-dprf: "Departamento de Polícia Rodoviária Federal (DPRF)"
      empresa-brasileira-de-infraestrutura-aeroportuaria-infraero: "Empresa Brasileira de Infraestrutura Aeroportuária (Infraero)"
      fundacao-nacional-do-indio-funai: "Fundação Nacional do Índio (Funai)"
      governo-municipal-governo-estadual-ou-a-companhia-nacional-de-abastecimento-conab: "Companhia Nacional de Abastecimento (Conab)"
      instituto-nacional-de-meteorologia: "Instituto Nacional de Meteorologia (Inmet)"
      instituto-nacional-de-meteorologia-inmet: "Instituto Nacional de Meteorologia (Inmet)"
      instituto-nacional-do-seguro-social: "Instituto Nacional do Seguro Social (INSS)"
      instituto-nacional-do-seguro-social-inss: "Instituto Nacional do Seguro Social (INSS)"
      ministerio-da-agricultura-pecuaria-e-abastecimento: "Ministério da Agricultura, Pecuária e Abastecimento (MAPA)"
      ministerio-da-agricultura-pecuaria-e-abastecimento-mapa: "Ministério da Agricultura, Pecuária e Abastecimento (MAPA)"
      ministerio-da-educacao-mec: "Ministério da Educação (MEC)"
      ministerio-da-fazenda: "Ministério da Fazenda (MF)"
      ministerio-da-fazenda-mf: "Ministério da Fazenda (MF)"
      ministerio-da-justica-mj: "Ministério da Justiça (MJ)"
      ministerio-da-pesca-e-aquicultura: "Ministério da Pesca e Aquicultura (MPA)"
      ministerio-da-pesca-e-aquicultura-mpa: "Ministério da Pesca e Aquicultura (MPA)"
      ministerio-da-previdencia-social: "Ministério da Previdência Social (MPS)"
      ministerio-da-previdencia-social-mps: "Ministério da Previdência Social (MPS)"
      ministerio-da-saude: "Ministério da Saúde (MS)"
      ministerio-da-saude-ms: "Ministério da Saúde (MS)"
      ministerio-do-desenvolvimento-agrario-mda: "Ministério do Desenvolvimento Agrário (MDA)"
      ministerio-do-desenvolvimento-social-e-combate-a-fome-mds: "Ministério do Desenvolvimento Social e Combate à Fome (MDS)"
      ministerio-do-planejamento-orcamento-e-gestao: "Ministério do Planejamento, Orçamento e Gestão (MPOG)"
      ministerio-do-trabalho-e-emprego-mte: "Ministério do Trabalho e Emprego (MTE)"
      ministerio-do-turismo: "Ministério do Turismo (MTur)"
      ministerio-do-turismo-mtur: "Ministério do Turismo (MTur)"
      municipio: "Município"
      receita-federal: "Secretaria da Receita Federal do Brasil (RFB)"
      receita-federal-do-brasil: "Secretaria da Receita Federal do Brasil (RFB)"
      receita-federal-do-brasil-rfb: "Secretaria da Receita Federal do Brasil (RFB)"
      receital-federal: "Secretaria da Receita Federal do Brasil (RFB)"
      secretaria-da-receita-federal-do-brasil-rfb: "Secretaria da Receita Federal do Brasil (RFB)"
      secretaria-de-aviacao-civil: "Secretaria de Aviação Civil"
      secretaria-de-planejamento-e-investimentos-estrategicos-spi: "Secretaria de Planejamento e Investimentos Estratégicos (SPI)"
      secretaria-do-patrimonio-da-uniao-spu-mp: "Secretaria do Patrimônio da União (SPU/MP)"
      secretaria-nacional-de-justica: "Secretaria Nacional de Justiça"
      secretaria-nacional-de-politicas-sobre-drogas-senad: "Secretaria Nacional de Políticas Sobre Drogas (Senad)"
      secretaria-nacional-de-seguranca-publica: "Secretaria Nacional de Segurança Pública"
    ouvidorias:
      arquivo-nacional: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/arquivo-nacional-an
      banco-central-do-brasil-bcb: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/bancos/banco-central-do-brasil-bacen
      companhia-nacional-de-abastecimento-conab: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/outras-estatais/companhia-nacional-de-abastecimento-conab
      defensoria-publica-da-uniao-dpu: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/defensoria-publica-da-uniao-dpu
      departamento-de-policia-federal-dpf: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/departamento-de-policia-federal-dpf
      departamento-de-policia-rodoviaria-federal-dprf: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/departamento-de-policia-rodoviaria-federal-dprf
      empresa-brasileira-de-infraestrutura-aeroportuaria-infraero: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/outras-estatais/empresa-brasileira-de-infraestrutura-aeroportuaria-infraero
      fundacao-nacional-do-indio-funai: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/outras-autarquias/fundacao-nacional-do-indio-funai
      ministerio-da-agricultura-pecuaria-e-abastecimento-mapa: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-agricultura-pecuaria-e-abastecimento-mapa
      ministerio-da-fazenda-mf: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-fazenda-mf
      ministerio-da-justica-mj: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-justica-mj
      ministerio-da-pesca-e-aquicultura-mpa: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-pesca-e-aquicultura-mpa
      ministerio-da-previdencia-social-mps: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-previdencia-social-mps
      ministerio-da-saude-ms: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-saude-ms
      ministerio-do-desenvolvimento-agrario-mda: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-desenvolvimento-agrario-mda
      ministerio-do-desenvolvimento-social-e-combate-a-fome-mds: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-desenvolvimento-social-e-combate-a-fome-mds
      ministerio-do-planejamento-orcamento-e-gestao-mpog: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-planejamento-orcamento-e-gestao-mpog
      ministerio-do-trabalho-e-emprego-mte: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-trabalho-e-emprego-mte
      ministerio-do-turismo-mtur: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-turismo-mtur
      secretaria-de-aviacao-civil: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/secretaria-de-aviacao-civil-sac
