spring:
  main:
    show-banner: false

  thymeleaf:
    mode: HTML5
    cache: false

server:
  port: ${port:8080}

gds:
    conteudo:
        termos:
            Abrir um negócio:  Administrar um negócio
            Administrar um negócio:  Administrar um negócio
            Adolescentes:  Adolescentes
            Aposentar-se:  Aposentar-se
            Aproveitando o tempo livre:  Aproveitar o tempo livre
            Cuidando da saúde:  Cuidar da saúde
            Emitindo meus documentos:  Emitir documentos
            Estudando:  Estudar
            Garantindo meus direitos:  Garantir direitos
            Indo para outro país:  Viajar
            Mantendo um veículo:  Manter um veículo
            Meu Negócio:  Administrar um negócio
            Meu negócio:  Administrar um negócio
            Obter Crédito e Apoio financeiro:  Obter crédito e apoio financeiro
            Pagando contas e impostos:  Pagar contas e impostos
            Prestando serviço militar:  Prestar serviço militar
            Procurando emprego:  Trabalhar
            Ter filhos:  Ter uma família
            Ter uma casa:  Ter uma casa
            Ter uma família:  Ter uma família
            Trabalhando:  Trabalhar
