spring:
  main:
    show-banner: false

  thymeleaf:
    cache: false

endpoints:
  health:
    sensitive: false

server:
  port: ${port:8080}

mail:
  protocol: smtp
  host: localhost
  port: 2500
  timeout: 5000
  smtp:
    auth: false
    starttls: false
  from: nao-responda@servicos.gov.br
  to: servicos@planejamento.gov.br
  username:
  password:

flags:
  importar.automaticamente: true
  permitir.robos: false
  destaques.automaticos: false

pds:
  importador.intervalo: '600000'
  piwik:
    enabled: false
    url: "https://estatisticas.presidencia.gov.br/"
    token: ""
    site: 52
  cartas:
    repositorio: "https://github.com/servicosgovbr/cartas-de-teste.git"
  destaques:
    servicos:
      - teste2
      - teste
    areasDeInteresse:
      - saude
