spring:
  main:
    show-banner: false

  thymeleaf:
    cache: false

endpoints:
  health:
    sensitive: false

server:
  port: ${port:8080}

mail:
  protocol: smtp
  host: localhost
  port: 2500
  timeout: 5000
  smtp:
    auth: false
    starttls: false
  from: nao-responda@servicos.gov.br
  to: servicos@planejamento.gov.br
  username:
  password:

gds:
  permitir-robos: false
  importar-automaticamente: false
  piwik:
    enabled: false
    url: "https://estatisticas.presidencia.gov.br/"
    token: ""
    site: 2
  destaques:
    servicos:
      - retificadora-on-line-extrato-da-dirpf
      - aposentadoria-por-invalidez
      - vistas-de-processo
  conteudo:
    linhasDaVida:
      abrir-um-negocio: Administrar um negócio
      trabalhando: Trabalhar
    orgaos:
      ministerio-da-previdencia-social-mps: Ministério da Previdência Social (MPS)
      ministerio-do-turismo: Ministério do Turismo
      ministerio-do-turismo-mtur: Ministério do Turismo
    ouvidorias:
      arquivo-nacional: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/arquivo-nacional-an
      banco-central-do-brasil-bcb: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/bancos/banco-central-do-brasil-bacen