spring:
  main:
    show-banner: false

  thymeleaf:
    mode: HTML5
    cache: false

server:
  port: ${port:8080}

gds:
  conteudo:
    linhasDaVida:
      Abrir um negócio: Administrar um negócio
      Trabalhando: Trabalhar
    orgaos:
      Ministério do Turismo: Ministério do Turismo
      Ministério do Turismo - MTur: Ministério do Turismo
      Ministério do Turismo- MTur: Ministério do Turismo