spring:
  main:
    show-banner: false

  thymeleaf:
    mode: HTML5
    cache: false

server:
  port: ${port:8080}

gds:
  destaques:
    servicos:
      - retificadora-on-line-extrato-da-dirpf
      - aposentadoria-por-invalidez
      - vistas-de-processo
  conteudo:
    linhasDaVida:
      abrir-um-negocio: Administrar um negócio
      trabalhando: Trabalhar
    orgaos:
      ministerio-da-previdencia-social-mps: Ministério da Previdência Social (MPS)
      ministerio-do-turismo: Ministério do Turismo
      ministerio-do-turismo-mtur: Ministério do Turismo